### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by simonschaufi**
- Use PSR-2 coding style
- remove composer.lock as this files should never be in the repository
- add doctypes
- move files to src folder

### CODE REVIEW

**Comment by sirprize** [comment]
Thanks for your PR but composer.lock must remain under VC - https://getcomposer.org/doc/01-basic-usage.md#commit-your-composer-lock-file-to-version-control

**Comment by simonschaufi** [comment]
@sirprize Adding the composer.lock is only relevant for projects, NOT for libraries (without dependencies).

**Comment by simonschaufi** [comment]
@sirprize ping! Please merge.

**Comment by sirprize** [comment]
Hi Simon - thanks for your ping, your work is now merged. I still would like to keep composer.lock so it is restored for 1.3.4 (see "Composer.lock in library" https://stackoverflow.com/questions/18901094/composer-lock-in-library)

**Comment by simonschaufi** [comment]
thank you. ok. got your point.

**Pull request merged**
